### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by BuethSam**

### CODE REVIEW

**Comment by hangxingliu** [comment]
I found there has a VS Code option named `http.proxy`. Do you think the following way is better:

Create a configuration named "codingTracker.proxy", its optional value are: "auto", "no-proxy", false or proxy URL. (and "auto" is the value by default)

And the real proxy should be the result merged from `http.proxy` and `codingTracker.proxy`. For example:

1. when `http.proxy` is `"http://127.0.0.1:8118"` and the `codingTracker.proxy` is not explicitly set. the option `proxy` for `request()` will be `"http://127.0.0.1:8118"`
2. when `http.proxy` is `"http://127.0.0.1:8118"` and the `codingTracker.proxy` is `false` or `"no-proxy"`. the option `proxy` for `request()` will be `null`
2. when `http.proxy` is `"http://127.0.0.1:8118"` and the `codingTracker.proxy` is `"http://192.168.88.88:8888"`. the option `proxy` for `request()` will be `"http://192.168.88.88:8888"`

**Comment by BuethSam** [comment]
well nice idea! but why make it more complicated than necessary
But thanks for considering my opinion

**Comment by hangxingliu** [comment]
And maybe just use `http.proxy` option just OK. The reason why I consider one more config item is becuase I am located in China (There are some strange reasons)

**Comment by BuethSam** [comment]
Okay just make your decision and tell me what the next step should be

**Comment by hangxingliu** [comment]
I will merge this pull request tomorrow or tonight. And modify somewhere to finish <https://github.com/hangxingliu/vscode-coding-tracker/pull/26#issuecomment-433154327> and I18N

**Comment by hangxingliu** [comment]
@BuethSam I push a new commit about network proxy. You can have a try. And I am welcome any feedback of it.

**Pull request merged**
